name: Deploy Innovatech Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test runner
        run: echo "Self-hosted runner received the deployment job"

      - name: Show files
        run: ls -la
